import { Client, DocumentKind, StudioSettings, money, safeUrl, totals } from "./studio";

const escape = (value: string) => value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const field = (value: string, placeholder: string) => escape(value || `[${placeholder}]`).replace(/\n/g, "<br>");
const section = (title: string, value: string, placeholder: string) => `<section><h2>${title}</h2><p>${field(value, placeholder)}</p></section>`;
export function documentBody(kind: DocumentKind, c: Client, s: StudioSettings) {
  const who = `<div class="facts"><div><small>Prepared for</small><p>${field(c.brand, "Client business")}<br>${field(c.contact, "Contact name")}<br>${field(c.email, "Client email")}</p></div><div><small>Prepared by</small><p>${field(s.legalName, "Legal business name")}<br>${field(s.email, "Business email")}<br>${field(s.address, "Business address")}</p></div></div>`;
  switch (kind) {
    case "Inquiry": return `<p class="intro">Tell us about your business and what you want to achieve.</p>${section("Your business", c.brand, "Business or brand name")}${section("What makes it special", c.brief, "What you do, who you serve and what makes you different")}${section("Your goals", c.goals, "What would you like to improve")}${section("Project", c.project, "Services needed")}${section("Budget and timing", [c.budget, c.timeline].filter(Boolean).join("\n"), "Budget range and preferred timing")}${section("Contact details", [c.contact, c.email, c.phone, c.website, c.instagram].filter(Boolean).join("\n"), "Name, email, phone, website and Instagram")}<p class="fine">Share only information relevant to this enquiry. Submission does not create an agreement.</p>`;
    case "Proposal": return `<p class="intro">${field(c.project, "Project name")}</p>${who}${section("The opportunity", c.goals, "The problem and the intended outcome")}${section("Scope and deliverables", c.scope, "List the deliverables and acceptance criteria")}${section("Outside this scope", c.exclusions, "Excluded work and third-party costs")}${section("Schedule", c.timeline, "Milestones, dependencies and target dates")}${section("Investment and payment", c.paymentTerms, "Quoted fee, deposit, milestones and proposal expiry")}${section("Revisions", c.revisions, "Included revision rounds")}<p class="fine">Draft proposal. Scope, price and timing require written approval before work begins.</p>`;
    case "Agreement": return `<p class="draft">DRAFT FOR REVIEW</p>${who}${section("Project", c.project, "Project name")}${section("Scope and acceptance", c.scope, "Deliverables and how they are approved")}${section("Exclusions", c.exclusions, "Excluded work, hosting, licences and advertising spend")}${section("Schedule and responsibilities", c.timeline, "Dates, client approvals, content and access responsibilities")}${section("Fees and payment", c.paymentTerms, "Fees, deposit, payment deadlines and suspension for overdue payment")}${section("Revisions and changes", c.revisions, "Revision allowance and written change approval process")}${section("Additional agreed terms", c.agreementTerms, "Complete ownership and licence terms, confidentiality, data handling, termination, liability, governing law and disputes with professional advice")}<div class="facts signatures"><div>For HyperScale<br><br>Name ___________________<br>Signature ________________<br>Date ____________________</div><div>For the client<br><br>Name ___________________<br>Signature ________________<br>Date ____________________</div></div><p class="fine">Unreviewed editable draft. This document does not record an electronic signature or acceptance. Obtain appropriate legal review before use.</p>`;
    case "Invoice": {
      const t = totals(c, s);
      return `<p class="draft">DRAFT INVOICE · AED</p>${who}<div class="facts"><p>Invoice number ${field(c.invoiceNumber, "Unique invoice number")}<br>Issued ${field(c.issueDate, "Issue date")}<br>Supply date ${field(c.supplyDate, "Supply date")}<br>Due ${field(c.dueDate, "Due date")}</p><p>Client address ${field(c.address, "Client address")}<br>Supplier TRN ${field(s.trn, "If registered")}<br>Client TRN ${field(c.clientTrn, "If registered")}</p></div><table><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>${c.lines.map(line => `<tr><td>${field(line.description, "Service description")}</td><td>${line.quantity}</td><td>${money(Math.round(line.rate * 100))}</td><td>${money(Math.round(line.quantity * Math.round(line.rate * 100)))}</td></tr>`).join("")}</tbody></table><div class="totals"><p>Subtotal <b>${money(t.subtotal)}</b></p><p>Discount <b>${money(t.discount)}</b></p><p>${s.vatRegistered ? `VAT draft calculation ${c.vatRate}%` : "VAT not configured"} <b>${money(t.vat)}</b></p><p>Total <b>${money(t.total)}</b></p><p>Paid <b>${money(t.paid)}</b></p><p>${t.balance < 0 ? "Credit balance" : "Amount due"} <b>${money(Math.abs(t.balance))}</b></p></div>${section("Payment instructions", s.bank, "Bank name, account holder, IBAN and payment reference")}${section("Payment terms", c.paymentTerms, "Agreed payment terms")}<p class="fine">Complete the business identity and check the tax treatment before issue. This is a draft billing template, not a verified UAE tax invoice or e-invoicing service.</p>`;
    }
    case "Welcome": return `<p class="intro">Welcome, ${field(c.brand, "Client name")}.</p><p>Thank you for choosing HyperScale. This pack brings together the next steps for your project.</p>${section("Your project", c.project, "Project name")}${section("Getting started", c.welcome, "Kickoff date, project contact, approved communication channel and required assets")}${section("What we will deliver", c.scope, "Confirmed deliverables")}${section("Schedule", c.timeline, "Key milestones and client review dates")}${section("Reviews and approvals", c.revisions, "How to submit consolidated feedback and who approves work")}<p>Share passwords through an agreed secure method. Do not put credentials in this document.</p>`;
    case "Client portal": return `<p class="intro">${field(c.brand, "Client")} · ${field(c.project, "Project")}</p>${section("Project update", c.portalMessage, "Your latest project update")}${section("Agreed scope", c.scope, "Shared deliverables")}${section("Schedule", c.timeline, "Shared milestones")}<section><h2>Milestones and tasks</h2>${c.tasks.filter(task => task.shared).map(task => `<p>${task.done ? "Complete" : "Upcoming"} · ${escape(task.title)}${task.due ? ` · ${escape(task.due)}` : ""}</p>`).join("") || "<p>No shared tasks yet.</p>"}</section><section><h2>Project links</h2>${c.sharedLinks.filter(link => safeUrl(link.url)).map(link => `<p><a href="${escape(safeUrl(link.url))}" target="_blank" rel="noopener noreferrer">${escape(link.title || "Project file")}</a></p>`).join("") || "<p>No shared links yet.</p>"}</section><p class="fine">Project snapshot. This file is not a live signed-in portal. Only the shared scope, schedule, update, tasks and links are included.</p><p><a href="${escape((safeUrl(s.website) || defaultWebsite).replace(/\/$/, ""))}/feedback">Send feedback</a></p>`;
    case "Feedback": return `<p class="intro">We would love to hear about your experience.</p>${section("Your project", c.project, "Project or business name")}${section("Why did you choose HyperScale", "", "Your answer")}${section("What did you find most valuable", "", "Your answer")}${section("What could we improve", c.feedback, "Your answer")}${section("Overall satisfaction", c.rating ? `${c.rating} out of 5` : "", "Choose 1 Very dissatisfied / 2 Dissatisfied / 3 Neutral / 4 Satisfied / 5 Very satisfied")}<p class="fine">Feedback is private unless you separately give permission to publish it as a testimonial.</p>`;
  }
}
const defaultWebsite = "https://mediumslateblue-badger-114133.hostingersite.com";
export function buildDocument(kind: DocumentKind, client: Client, settings: StudioSettings, logo = "", editable = true) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HyperScale ${escape(kind)} ${escape(client.brand)}</title><style>
*{box-sizing:border-box}body{margin:0;background:#e9ece7;color:#111c18;font:15px/1.65 Arial,sans-serif}header{padding:14px 24px;background:#11251d;color:white;display:flex;gap:14px;align-items:center;position:sticky;top:0;z-index:2}button{padding:10px 16px;background:#ceef58;border:0;color:#11251d;cursor:pointer;font:inherit}article{background:#fffef8;max-width:820px;margin:32px auto;padding:58px 60px;min-height:1040px}.brand{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #c7d1c5;padding-bottom:22px;margin-bottom:42px}.brand img{width:44px;height:44px;object-fit:contain}.brand strong{font-size:18px;letter-spacing:2px}h1{font-size:58px;line-height:1.05;letter-spacing:-2px;margin:0 0 28px}h2{font-size:16px;margin:0 0 10px}p{margin:0 0 14px;overflow-wrap:anywhere}section{margin:28px 0;break-inside:avoid}.intro{font-size:23px}.draft,small{font-size:11px;letter-spacing:1.2px;text-transform:uppercase}.draft{padding-bottom:18px;color:#526148}.facts{display:grid;grid-template-columns:1fr 1fr;gap:32px;margin:24px 0}.fine{font-size:11px;color:#526148;margin-top:30px}.signatures{margin-top:45px;break-inside:avoid}table{width:100%;border-collapse:collapse;margin:28px 0;font-size:12px}th,td{text-align:left;padding:12px 8px;border:1px solid #ced4c8;overflow-wrap:anywhere}th{background:#eaf2d8}th:first-child{width:44%}.totals{margin-left:auto;max-width:320px}.totals p{display:flex;justify-content:space-between;border-bottom:1px solid #dce1d7;padding:8px 0;margin:0}.totals p:last-child{font-size:19px}a{color:#174631}[contenteditable]:focus{outline:2px solid #95b339}footer{border-top:1px solid #c7d1c5;padding-top:20px;margin-top:45px;font-size:11px}footer a{overflow-wrap:anywhere}@media(max-width:600px){article{margin:0;padding:30px 22px;min-height:0}h1{font-size:42px}.facts{grid-template-columns:1fr}header{flex-wrap:wrap}table{font-size:10px}}@page{size:A4;margin:16mm}@media print{header{display:none}body{background:white;font-size:11pt}article{margin:0;padding:0;max-width:none;min-height:0}h1{font-size:40pt}a{color:inherit;text-decoration:none}.brand{margin-bottom:25px}section{margin:20px 0}footer{margin-top:30px}}
</style></head><body><header><b>HYPERSCALE</b><button onclick="window.print()">Print / Save PDF</button>${editable ? '<button onclick="saveCopy()">Save edited copy</button><span>Edit the document below.</span>' : ''}</header><article ${editable ? 'contenteditable="true" spellcheck="true"' : ''}><div class="brand"><strong>HYPERSCALE</strong>${logo ? `<img src="${escape(logo)}" alt="HyperScale">` : ''}</div><h1>${escape(kind === "Welcome" ? "Welcome pack" : kind === "Client portal" ? "Your project" : kind === "Inquiry" ? "Project enquiry" : kind)}</h1>${documentBody(kind, client, settings)}<footer>HyperScale · <a href="${escape(safeUrl(settings.website) || defaultWebsite)}">${escape(settings.website)}</a></footer></article>${editable ? `<script>function saveCopy(){const html='<!doctype html>'+document.documentElement.outerHTML;const url=URL.createObjectURL(new Blob([html],{type:'text/html'}));const a=document.createElement('a');a.href=url;a.download='HyperScale-edited-document.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}</script>` : ''}</body></html>`;
}
