import { useEffect, useState } from "react";
import { Link } from "wouter";
import { Client, defaultSettings, documentKinds, downloadFile, fileName, newClient, parseBackup, stages, STORAGE_KEY, StudioSettings, StudioStore, totals, money, inquirySchema, feedbackSchema } from "@/lib/studio";
import { buildDocument } from "@/lib/studio-documents";
import "./studio.css";

type Tab = "Brief" | "Project" | "Billing" | "Portal" | "Feedback";
function Field({ label, value, onChange, multiline = false, type = "text" }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean; type?: string }) {
  return <label className={multiline ? "st-field st-wide" : "st-field"}><span>{label}</span>{multiline ? <textarea rows={4} maxLength={12000} value={value} onChange={event => onChange(event.target.value)} /> : <input type={type} maxLength={500} value={value} onChange={event => onChange(event.target.value)} />}</label>;
}
function NumberField({ label, value, onChange, max = 100000000 }: { label: string; value: number; onChange: (value: number) => void; max?: number }) {
  return <label className="st-field"><span>{label}</span><input type="number" min="0" max={max} step="0.01" value={value} onChange={event => { const n = Number(event.target.value); if (Number.isFinite(n) && n >= 0 && n <= max) onChange(n); }} /></label>;
}
function initialState() {
  try { const raw = localStorage.getItem(STORAGE_KEY); return { data: raw ? parseBackup(raw) : { version: 1 as const, settings: defaultSettings, clients: [] }, error: "" }; }
  catch { return { data: { version: 1 as const, settings: defaultSettings, clients: [] }, error: "Stored records could not be opened. They have not been overwritten. Restore a backup below or download the stored data before resetting." }; }
}
export default function Studio() {
  const [initial] = useState(initialState);
  const [data, setData] = useState<StudioStore>(initial.data);
  const [storageError, setStorageError] = useState(initial.error);
  const [locked, setLocked] = useState(!!initial.error);
  const [saved, setSaved] = useState(false);
  const [view, setView] = useState<"Clients" | "Materials" | "Settings">("Clients");
  const [selected, setSelected] = useState<string>(initial.data.clients[0]?.id || "");
  const [tab, setTab] = useState<Tab>("Brief");
  const [search, setSearch] = useState("");
  const [preview, setPreview] = useState<{ html: string; name: string } | null>(null);
  const [pendingRestore, setPendingRestore] = useState<StudioStore | null>(null);
  const [notice, setNotice] = useState("");
  const [logo, setLogo] = useState("");
  const client = data.clients.find(c => c.id === selected);
  useEffect(() => { fetch("/brand/hyperscale-h.png").then(r => r.blob()).then(blob => { const reader = new FileReader(); reader.onload = () => setLogo(String(reader.result)); reader.readAsDataURL(blob); }).catch(() => {}); }, []);
  useEffect(() => {
    if (locked) return;
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); setSaved(true); setStorageError(""); }
    catch { setSaved(false); setStorageError("Changes are only in memory. Browser storage is unavailable or full. Download a backup now before closing this page."); }
  }, [data, locked]);
  function update(patch: Partial<Client>) { if (locked || !client) return; setData(d => ({ ...d, clients: d.clients.map(c => c.id === client.id ? { ...c, ...patch } : c) })); }
  function setting(patch: Partial<StudioSettings>) { if (!locked) setData(d => ({ ...d, settings: { ...d.settings, ...patch } })); }
  function addClient() { if (locked) return; if (data.clients.length >= 2000) { setNotice("This workspace supports up to 2,000 clients. Export a backup before archiving records."); return; } const c = newClient(); setData(d => ({ ...d, clients: [...d.clients, c] })); setSelected(c.id); setTab("Brief"); setView("Clients"); }
  async function restore(file?: File) {
    if (!file) return;
    try { if (file.size > 10000000) throw new Error("File too large"); setPendingRestore(parseBackup(await file.text())); setNotice(""); }
    catch { setNotice("This is not a valid HyperScale backup. Your current records are unchanged."); }
  }
  async function importResponse(file?: File) {
    if (!file || locked) return;
    try {
      if (file.size > 100000) throw new Error("File too large");
      const raw = JSON.parse(await file.text());
      if (raw.kind === "hyperscale-inquiry") {
        const { kind: _kind, service, ...inquiry } = inquirySchema.parse(raw);
        if (data.clients.length >= 2000) throw new Error("Workspace full");
        const c = { ...newClient(), ...inquiry, project: service };
        setData(d => ({ ...d, clients: [...d.clients, c] })); setSelected(c.id); setTab("Brief");
        setNotice(`Imported enquiry for ${c.brand}. Review the client details.`);
      } else {
        const feedback = feedbackSchema.parse(raw);
        if (!client) throw new Error("No selected client");
        if (!window.confirm(`Apply feedback for ${feedback.brand} to the selected client ${client.brand}? This replaces their recorded feedback.`)) return;
        update({ rating: feedback.rating, feedback: `Why they chose us: ${feedback.why}\n\nMost valuable: ${feedback.valuable}\n\nImprovements: ${feedback.improve}` }); setTab("Feedback"); setNotice("Feedback imported.");
      }
    } catch { setNotice("Could not import this response. Use a downloaded HyperScale enquiry or feedback JSON. Select the correct client before importing feedback."); }
  }
  function generate(kind: typeof documentKinds[number], blank = false) {
    const c = blank ? { ...newClient(), brand: "", issueDate: "" } : client;
    if (!c) { setNotice("Choose or create a client first."); return; }
    setPreview({ html: buildDocument(kind, c, data.settings, logo, kind !== "Client portal"), name: `HyperScale-${fileName(c.brand)}-${fileName(kind)}.html` });
  }
  const cField = (key: keyof Client, label: string, multiline = false, type = "text") => client && <Field key={key} label={label} value={String(client[key])} onChange={value => update({ [key]: value })} multiline={multiline} type={type} />;
  const balance = client && totals(client, data.settings);
  return <div className="studio" dir="ltr"><aside className="st-sidebar"><a className="st-brand" href="/dashboard"><img src="/brand/hyperscale-h.png" alt="" /><span>HYPERSCALE<small>Studio dashboard</small></span></a><nav aria-label="Dashboard">{(["Clients", "Materials", "Settings"] as const).map(item => <button key={item} aria-current={view === item ? "page" : undefined} onClick={() => { setView(item); setPreview(null); }}>{item}</button>)}</nav><div className="st-sidebar-bottom"><Link href="/">View website</Link><Link href="/inquiry">Project enquiry</Link><Link href="/feedback">Feedback form</Link><p>Local workspace<br />No cloud sync or sign-in</p></div></aside>
  <main className="st-main"><header className="st-top"><span>{view}</span><span role="status">{locked ? "Recovery required" : saved ? "Saved in this browser" : "Not saved"}</span><button onClick={() => downloadFile(`HyperScale-backup-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify(data, null, 2), "application/json")}>Download backup</button></header>
  <p className="st-local">Client records stay in this browser on this device. Download backups regularly. Use a private browser profile on a shared computer.</p>
  {storageError && <div className="st-error" role="alert">{storageError}{locked && <><button onClick={() => downloadFile("HyperScale-recovery-data.txt", localStorage.getItem(STORAGE_KEY) || "", "text/plain")}>Download stored data</button><button onClick={() => { if (window.confirm("Reset this browser workspace? First download the stored data. This removes the unreadable local copy.")) { setLocked(false); setStorageError(""); } }}>Reset workspace</button></>}</div>}
  {notice && <p role="status" className="st-notice">{notice}</p>}
  {pendingRestore && <section className="st-restore"><h2>Restore backup</h2><p>This backup contains {pendingRestore.clients.length} clients. Restoring replaces the {data.clients.length} clients currently in this browser.</p><button onClick={() => { setData(pendingRestore); setSelected(pendingRestore.clients[0]?.id || ""); setPendingRestore(null); setLocked(false); setNotice("Backup restored."); }}>Replace with this backup</button><button onClick={() => setPendingRestore(null)}>Cancel</button></section>}
  {preview ? <section className="st-preview"><div><h1>Document preview</h1><button onClick={() => downloadFile(preview.name, preview.html)}>Download HTML</button><button onClick={() => setPreview(null)}>Close preview</button></div><p>Use the document’s Print / Save PDF control. Edited document copies are separate from client records.</p><iframe title="Generated client document" srcDoc={preview.html} sandbox="allow-scripts allow-modals allow-downloads" /></section> : <>
  {view === "Clients" && <><div className="st-page-title"><div><span className="st-kicker">YOUR CLIENT WORKFLOW</span><h1>From enquiry to delivery.</h1></div><button className="st-primary" onClick={addClient} disabled={locked}>New client</button></div><label className="st-field st-import"><span>Import an enquiry or feedback response</span><input type="file" disabled={locked} accept=".json,application/json" onChange={e => { void importResponse(e.target.files?.[0]); e.target.value = ""; }} /></label><div className="st-pipeline">{stages.map(stage => <div key={stage}><strong>{data.clients.filter(c => c.stage === stage).length}</strong><span>{stage}</span></div>)}</div><div className="st-workspace"><section className="st-client-list"><label className="st-field"><span>Find a client</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search by name or project" /></label>{data.clients.filter(c => `${c.brand} ${c.project}`.toLowerCase().includes(search.toLowerCase())).map(c => <button key={c.id} className={selected === c.id ? "active" : ""} onClick={() => { setSelected(c.id); setTab("Brief"); }}><strong>{c.brand || "Untitled client"}</strong><small>{c.stage} · {c.project || "No project yet"}</small></button>)}{!data.clients.length && <p>No clients yet. Create your first client to start a project.</p>}</section>
  {client ? <section className="st-editor"><div className="st-client-title"><h2>{client.brand || "Untitled client"}</h2><label>Stage<select value={client.stage} onChange={e => update({ stage: e.target.value as Client["stage"] })}>{stages.map(stage => <option key={stage}>{stage}</option>)}</select></label></div><div className="st-tabs" role="tablist" aria-label="Client details">{(["Brief", "Project", "Billing", "Portal", "Feedback"] as const).map(item => <button role="tab" aria-selected={tab === item} key={item} onClick={() => setTab(item)}>{item}</button>)}</div><fieldset disabled={locked} className="st-fields">
  {tab === "Brief" && <>{cField("brand", "Business or brand")}{cField("contact", "Contact name")}{cField("email", "Client email", false, "email")}{cField("phone", "Phone", false, "tel")}{cField("website", "Website")}{cField("instagram", "Instagram")}{cField("brief", "About the business", true)}{cField("goals", "Goals", true)}{cField("budget", "Budget range")}{cField("project", "Project name")}{cField("address", "Client address", true)}{cField("notes", "Internal notes — never included in the portal", true)}</>}
  {tab === "Project" && <>{cField("project", "Project name")}{cField("revisions", "Included revisions and approval process")}{cField("scope", "Scope and acceptance criteria", true)}{cField("exclusions", "Excluded work and third-party costs", true)}{cField("timeline", "Schedule and responsibilities", true)}{cField("paymentTerms", "Fees and payment terms", true)}{cField("agreementTerms", "Additional agreement terms — draft for review", true)}{cField("welcome", "Welcome and kickoff instructions", true)}</>}
  {tab === "Billing" && <>{cField("invoiceNumber", "Unique invoice number")}{cField("issueDate", "Issue date", false, "date")}{cField("supplyDate", "Supply date", false, "date")}{cField("dueDate", "Due date", false, "date")}{cField("clientTrn", "Client TRN if registered")}<div className="st-wide st-lines"><h3>Invoice items · AED</h3>{client.lines.map((line, i) => <div className="st-line" key={i}><Field label="Description" value={line.description} onChange={description => update({ lines: client.lines.map((item, j) => j === i ? { ...item, description } : item) })} /><NumberField label="Quantity" value={line.quantity} max={100000} onChange={quantity => update({ lines: client.lines.map((item, j) => j === i ? { ...item, quantity } : item) })} /><NumberField label="Unit price AED" value={line.rate} onChange={rate => update({ lines: client.lines.map((item, j) => j === i ? { ...item, rate } : item) })} /><button onClick={() => update({ lines: client.lines.filter((_, j) => j !== i) })} type="button" aria-label={`Remove item ${i + 1}`}>Remove</button></div>)}<button type="button" onClick={() => update({ lines: [...client.lines, { description: "", quantity: 1, rate: 0 }] })} disabled={client.lines.length >= 100}>Add item</button></div><NumberField label="Discount AED" value={client.discount} onChange={discount => update({ discount })} /><NumberField label="Payment received AED" value={client.paid} onChange={paid => update({ paid })} />{data.settings.vatRegistered && <NumberField label="Draft VAT rate %" max={100} value={client.vatRate} onChange={vatRate => update({ vatRate })} />}<p className="st-wide">Total {balance && money(balance.total)} · {balance && balance.balance < 0 ? "Credit" : "Balance"} {balance && money(Math.abs(balance.balance))}</p><p className="st-wide">Invoices remain drafts. Complete the business details and review tax treatment before issuing.</p></>}
  {tab === "Portal" && <>{cField("portalMessage", "Shared project update", true)}<div className="st-wide"><h3>Tasks and milestones</h3>{client.tasks.map(task => <div className="st-task" key={task.id}><label><input type="checkbox" checked={task.done} onChange={e => update({ tasks: client.tasks.map(t => t.id === task.id ? { ...t, done: e.target.checked } : t) })} />Complete</label><Field label="Task" value={task.title} onChange={title => update({ tasks: client.tasks.map(t => t.id === task.id ? { ...t, title } : t) })} /><Field label="Due date" type="date" value={task.due} onChange={due => update({ tasks: client.tasks.map(t => t.id === task.id ? { ...t, due } : t) })} /><label><input type="checkbox" checked={task.shared} onChange={e => update({ tasks: client.tasks.map(t => t.id === task.id ? { ...t, shared: e.target.checked } : t) })} />Share in portal</label><button type="button" onClick={() => update({ tasks: client.tasks.filter(t => t.id !== task.id) })}>Remove</button></div>)}<button type="button" disabled={client.tasks.length >= 500} onClick={() => update({ tasks: [...client.tasks, { id: crypto.randomUUID(), title: "", due: "", done: false, shared: false }] })}>Add task</button></div><div className="st-wide"><h3>Shared project links</h3>{client.sharedLinks.map((link, i) => <div className="st-line" key={i}><Field label="Title" value={link.title} onChange={title => update({ sharedLinks: client.sharedLinks.map((l, j) => i === j ? { ...l, title } : l) })} /><Field label="HTTPS link" value={link.url} onChange={url => update({ sharedLinks: client.sharedLinks.map((l, j) => i === j ? { ...l, url } : l) })} /><button type="button" onClick={() => update({ sharedLinks: client.sharedLinks.filter((_, j) => j !== i) })}>Remove</button></div>)}<button type="button" disabled={client.sharedLinks.length >= 100} onClick={() => update({ sharedLinks: [...client.sharedLinks, { title: "", url: "" }] })}>Add link</button></div><p className="st-wide">Export a separate snapshot for this client. It contains the shared scope, schedule, update, selected tasks and links. Internal notes, billing and other clients are excluded. Check link permissions before sharing.</p></>}
  {tab === "Feedback" && <><label className="st-field"><span>Overall satisfaction</span><select value={client.rating} onChange={e => update({ rating: Number(e.target.value) })}><option value="0">Not recorded</option>{["Very dissatisfied", "Dissatisfied", "Neutral", "Satisfied", "Very satisfied"].map((label, i) => <option key={label} value={i + 1}>{i + 1} · {label}</option>)}</select></label>{cField("feedback", "Private feedback received", true)}<p className="st-wide">Record feedback received from the client. Publishing a testimonial requires separate permission.</p></>}
  </fieldset><div className="st-doc-actions"><h3>Create a document</h3>{documentKinds.map(kind => <button key={kind} onClick={() => generate(kind)}>{kind}</button>)}</div><button className="st-delete" onClick={() => { if (window.confirm(`Delete ${client.brand} and all its records from this browser? Download a backup first.`)) { setData(d => ({ ...d, clients: d.clients.filter(c => c.id !== client.id) })); setSelected(""); } }} disabled={locked}>Delete client</button></section> : <section className="st-empty"><h2>Your client workspace</h2><p>Choose a client to manage the brief, project, billing and delivery.</p></section>}</div></>}
  {view === "Materials" && <><div className="st-page-title"><div><span className="st-kicker">EDITABLE AND PRINTABLE</span><h1>Your document library.</h1></div></div><p>Open a blank template, edit it directly, then save a copy or print it. Use the client workspace to fill it with client details.</p><div className="st-materials">{documentKinds.map(kind => <button key={kind} onClick={() => generate(kind, true)}><strong>{kind}</strong><span>Open editable template</span></button>)}</div></>}
  {view === "Settings" && <><div className="st-page-title"><div><span className="st-kicker">YOUR BUSINESS</span><h1>Make it yours.</h1></div></div><fieldset className="st-fields st-settings" disabled={locked}>{([ ["legalName", "Legal business name"], ["email", "Business email"], ["phone", "Business phone"], ["website", "Website or preview link"], ["address", "Postal address"], ["bank", "Payment instructions"], ["trn", "Supplier TRN if registered"] ] as [keyof StudioSettings, string][]).map(([key, label]) => <Field key={key} label={label} value={String(data.settings[key])} multiline={key === "address" || key === "bank"} onChange={value => setting({ [key]: value })} />)}<label className="st-wide"><input type="checkbox" checked={data.settings.vatRegistered} onChange={e => setting({ vatRegistered: e.target.checked })} /> Business is VAT registered — enable draft calculations</label><p className="st-wide">No business identity, bank details or tax registration is assumed. Check every invoice and agreement before use.</p></fieldset><section className="st-backup"><h2>Backups and recovery</h2><p>Keep backup files privately. They include all client records and business details. Clearing browser data removes this workspace.</p><label className="st-field"><span>Restore a HyperScale JSON backup</span><input type="file" accept=".json,application/json" onChange={e => { void restore(e.target.files?.[0]); e.target.value = ""; }} /></label></section></>}
  </> }</main></div>;
}
