import { useState } from "react";
import { Link } from "wouter";
import { useLocale } from "@/contexts/LocaleContext";
import { downloadFile } from "@/lib/studio";
import { Shell } from "./Home";
import { Footer } from "./Experience";
import "./workflow.css";

export default function WorkflowForm({ feedback = false }: { feedback?: boolean }) {
  const { t } = useLocale();
  const [age, setAge] = useState("");
  const [step, setStep] = useState(0);
  const [values, setValues] = useState<Record<string, string>>({});
  const [consent, setConsent] = useState(false);
  const eligible = /^\d{1,3}$/.test(age) && Number(age) >= 13 && Number(age) <= 120;
  const underAge = /^\d{1,3}$/.test(age) && Number(age) < 13;
  const set = (key: string, value: string) => setValues(v => ({ ...v, [key]: value }));
  function input(key: string, english: string, arabic: string, required = false, textarea = false, type = "text") {
    return <label className={textarea ? "wf-wide" : ""}><span>{t(english, arabic)}{required ? " *" : ""}</span>{textarea ? <textarea required={required} rows={4} maxLength={3000} value={values[key] || ""} onChange={event => set(key, event.target.value)} /> : <input required={required} type={type} maxLength={key === "email" ? 254 : 300} value={values[key] || ""} onChange={event => set(key, event.target.value)} />}</label>;
  }
  function response() {
    return feedback ? { kind: "hyperscale-feedback", brand: values.brand || "", why: values.why || "", valuable: values.valuable || "", improve: values.improve || "", rating: Number(values.rating || 0) } : { kind: "hyperscale-inquiry", brand: values.brand || "", brief: values.brief || "", website: values.website || "", instagram: values.instagram || "", goals: values.goals || "", service: values.service || "", budget: values.budget || "", timeline: values.timeline || "", contact: values.contact || "", email: values.email || "", phone: values.phone || "" };
  }
  function message() {
    return Object.entries(response()).filter(([key, value]) => key !== "kind" && value).map(([key, value]) => `${key[0].toUpperCase() + key.slice(1)}: ${value}`).join("\n\n");
  }
  return <Shell><main className="experience xp-inner wf-page"><div className="wf-heading"><span className="xp-eyebrow">{feedback ? t("Your experience", "تجربتك") : t("Start a project", "ابدأ مشروعًا")}</span><h1>{feedback ? t("How did we do?", "كيف كانت تجربتك؟") : t("Tell us about your business.", "أخبرنا عن شركتك.")}</h1></div><div className="wf-layout"><section className="wf-form"><label className="wf-age"><span>{t("Your age", "عمرك")}</span><input type="number" min="0" max="120" step="1" inputMode="numeric" autoComplete="off" value={age} onChange={event => { setAge(event.target.value); if (Number(event.target.value) < 13 || Number(event.target.value) > 120) { setValues({}); setConsent(false); setStep(0); } }} /><small>{t("Checked before contact fields appear. Your age is not saved or included in your response.", "يتم التحقق قبل ظهور حقول التواصل. لن يُحفظ عمرك أو يُضمّن في الرد.")}</small></label>{underAge && <p role="alert">{t("This form is unavailable for the age entered.", "النموذج غير متاح للعمر المدخل.")}</p>}
  {eligible && <form onSubmit={event => { event.preventDefault(); if (!feedback && step < 2) { setStep(step + 1); return; } if (!consent) return; window.location.assign(`https://wa.me/971566997831?text=${encodeURIComponent(`Hello HyperScale, ${feedback ? "here is my feedback" : "I would like to discuss a project"}:\n\n${message()}`)}`); }}>
    {!feedback && <nav className="wf-steps" aria-label={t("Enquiry steps", "خطوات الاستفسار")}>{[t("Business", "الشركة"), t("Project", "المشروع"), t("Contact", "التواصل")].map((label, i) => <span aria-current={step === i ? "step" : undefined} key={label}>{label}</span>)}</nav>}
    <div className="wf-grid">
    {feedback ? <>{input("brand", "Business or project name", "اسم الشركة أو المشروع", true)}{input("why", "Why did you choose HyperScale?", "لماذا اخترت هايبرسكيل؟", false, true)}{input("valuable", "What was most valuable?", "ما أكثر شيء أفادك؟", true, true)}{input("improve", "What could we improve?", "ما الذي يمكننا تحسينه؟", false, true)}<fieldset className="wf-rating wf-wide"><legend>{t("Overall satisfaction", "الرضا العام")} *</legend>{[t("Very dissatisfied", "غير راضٍ إطلاقًا"), t("Dissatisfied", "غير راضٍ"), t("Neutral", "محايد"), t("Satisfied", "راضٍ"), t("Very satisfied", "راضٍ جدًا")].map((label, i) => <label key={label}><input type="radio" name="rating" required value={i + 1} checked={values.rating === String(i + 1)} onChange={event => set("rating", event.target.value)} /><span>{label}</span></label>)}</fieldset></> : step === 0 ? <>{input("brand", "Business or brand name", "اسم الشركة أو العلامة", true)}{input("instagram", "Instagram (optional)", "إنستغرام (اختياري)")}{input("brief", "What do you do and what makes it special?", "ماذا تقدم وما الذي يميزك؟", true, true)}{input("website", "Website (optional)", "الموقع الإلكتروني (اختياري)")}</> : step === 1 ? <>{input("goals", "What would you like to achieve?", "ما الذي تريد تحقيقه؟", true, true)}<label><span>{t("Service", "الخدمة")} *</span><select required value={values.service || ""} onChange={event => set("service", event.target.value)}><option value="">{t("Choose a service", "اختر خدمة")}</option>{[["Website", "موقع إلكتروني"], ["Performance marketing", "تسويق بالأداء"], ["Growth strategy", "استراتيجية النمو"], ["E-commerce", "التجارة الإلكترونية"], ["Creative", "الإبداع"], ["AI and automation", "الذكاء الاصطناعي والأتمتة"], ["Not sure yet", "لم أحدد بعد"]].map(([en, ar]) => <option value={en} key={en}>{t(en, ar)}</option>)}</select></label>{input("budget", "Budget range (optional)", "نطاق الميزانية (اختياري)")}{input("timeline", "Preferred timing (optional)", "التوقيت المفضل (اختياري)")}</> : <>{input("contact", "Your name", "اسمك", true)}{input("email", "Email", "البريد الإلكتروني", true, false, "email")}{input("phone", "Phone (optional)", "الهاتف (اختياري)", false, false, "tel")}<div className="wf-wide wf-summary"><h2>{t("Your project", "مشروعك")}</h2><p>{values.brand} · {values.service}</p><p>{values.goals}</p></div></>}
    </div>
    {(feedback || step === 2) && <><label className="wf-consent"><input type="checkbox" required checked={consent} onChange={event => setConsent(event.target.checked)} /><span>{t("I agree to share these details to discuss my enquiry or feedback. Read the", "أوافق على مشاركة هذه التفاصيل لمناقشة الاستفسار أو الملاحظات. اقرأ")} <Link href="/privacy">{t("Privacy Policy", "سياسة الخصوصية")}</Link>.</span></label><p className="wf-delivery">{t("Your response opens in WhatsApp for you to review and send. This website does not submit or save it.", "سيفتح ردك في واتساب لتراجعه وترسله. لا يرسل الموقع ردك ولا يحفظه.")}</p></>}
    <div className="wf-actions">{!feedback && step > 0 && <button type="button" onClick={() => setStep(step - 1)}>{t("Back", "رجوع")}</button>}<button className="wf-primary" type="submit">{!feedback && step < 2 ? t("Continue", "متابعة") : t("Continue in WhatsApp", "المتابعة في واتساب")}</button>{(feedback || step === 2) && <button type="button" onClick={event => { const form = event.currentTarget.form; if (!form?.reportValidity() || !consent) return; downloadFile(feedback ? "HyperScale-feedback.json" : "HyperScale-project-enquiry.json", JSON.stringify(response(), null, 2), "application/json"); }}>{t("Download a copy", "تنزيل نسخة")}</button>}</div>
  </form>}
  </section><aside className="wf-aside"><h2>{feedback ? t("Thank you for your feedback.", "شكرًا لملاحظاتك.") : t("A good project starts with a conversation.", "المشروع الجيد يبدأ بمحادثة.")}</h2><p>{feedback ? t("Your response stays private. We will ask separately before publishing a testimonial.", "يبقى ردك خاصًا. سنطلب إذنًا منفصلًا قبل نشر شهادة.") : t("We will review your goals and discuss a suitable scope before preparing a proposal.", "سنراجع أهدافك ونناقش نطاقًا مناسبًا قبل إعداد العرض.")}</p><a href="mailto:hello@hyperscale.marketing">hello@hyperscale.marketing</a><a href="tel:+971566997831">+971 56 699 7831</a></aside></div></main><Footer /></Shell>;
}
export function InquiryPage() { return <WorkflowForm />; }
export function FeedbackPage() { return <WorkflowForm feedback />; }
